print('10 de febrero de 2023')
print(' ')
print(' ')
print(' ')
print('No se como me siento. Muchos sentimientos encontrados.')
print('Quiero logras aprender este maravilloso lenguaje de programacion.')
print('Lo grogaste')
print('☺️')